markdown: redcarpet
pygments: true
permalink: posts/:title
auto: true

name: Poplus
author: Fundación Ciudadano Inteligente
featured-image: //images/post/
url: http://poplus.org/
description: Poplus project.
twitter: ciudadanoi
github: ciudadanointeligente
gravatar_url: http://gravatar.com/avatar/6f63cde8b16b035280ca615f621a6c8c
hashtag: '#Poplus'
disqus:
  shortname: poplus

analytics :
  provider : google
  google :
      tracking_id : 'UA-39677523-2'